Master
sergey-berezin/s02170251 pull request #1
Opened 2020-10-05 07:35 UTC by NickZorander

pull request

2020-10-05 08:52 UTC, NickZorander commented
надеюсь этот пулреквест сработает

2020-10-07 07:54 UTC, sergey-berezin requested changes

2020-10-14 07:09 UTC, sergey-berezin requested changes

2020-10-14 07:09 UTC, sergey-berezin commented on DigitRecognition/Recognizer.cs
> +        public Recognizer (ManualResetEvent wH, IResultOutput outpObj)
Зачем wH создавать снаружи конструктора? Это усложняет использование компонента.

2020-10-14 07:09 UTC, sergey-berezin commented on DigitRecognition/Recognizer.cs
>              }
Как определить, что все изображения распознаны и процесс распознавания завершен?

2020-10-14 08:03 UTC, sergey-berezin approved these changes

2020-10-14 08:04 UTC, merged